# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ILA/ILA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA || ORIG_REF_NAME==ILA}]

# IP: bd/ILA/ip/ILA_ila_0_0/ILA_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_ila_0_0 || ORIG_REF_NAME==ILA_ila_0_0}]

# IP: bd/ILA/ip/ILA_processing_system7_0_0/ILA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_processing_system7_0_0 || ORIG_REF_NAME==ILA_processing_system7_0_0}]

# IP: bd/ILA/ip/ILA_Dual_MCP3313_0_0/ILA_Dual_MCP3313_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_Dual_MCP3313_0_0 || ORIG_REF_NAME==ILA_Dual_MCP3313_0_0}]

# IP: bd/ILA/ip/ILA_xlconstant_0_1/ILA_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_xlconstant_0_1 || ORIG_REF_NAME==ILA_xlconstant_0_1}]

# XDC: bd/ILA/ILA_ooc.xdc
